version: "3.9"
services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
    ports:
      - "80:80"
  postgres:
    image: 'postgres'
    platform: linux/arm64
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  grpc:
    build: .
    ports:
      - "50051:50051"
    volumes: 
      - .:/data/app
    depends_on: 
      - postgres
volumes: 
  data: